### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by sowd** [KAIT-HEMS/PicoGW#1]
My acquaintance reported current PicoGW does not work on FreeBSD.
It may be caused by the arp library I am using does not support FreeBSD.

I will check later and report here.

The log:
=====
/usr/home/myname/PicoGW/node_modules/arped/lib/fetchers/ARP.js:25
           throw new Error('Not Implemented');
           ^

Error: Not Implemented
   at GenericARP.fetch (/usr/home/myname/PicoGW/node_modules/arped/lib/fetchers/ARP.js:25:19)
   at Arped.table (/usr/home/myname/PicoGW/node_modules/arped/lib/index.js:45:36)
   at chkArpTable [as _repeat] (/usr/home/myname/PicoGW/v1/plugins/admin/ipv4.js:85:22)
   at wrapper [as _onTimeout] (timers.js:276:11)
   at Timer.listOnTimeout (timers.js:93:15)

**Comment by sowd** [comment]
ARP management improved. PicoGW now works on Windows, MacOS, and Termux (Android app).
FreeBSD may be worth trying.

**Comment by sowd** [comment]
New picogw works on FreeBSD.
http://lifedesign.tech/2018/02/freebsd-picogw/
